import { ToolDefinition } from "./types";

export const TDI_TOOLCHAIN: readonly ToolDefinition[] = [
  {
    id: "codeql",
    tier: "A",
    version: "2.27.1",
    outputFormat: "sarif-2.1.0",
    purpose: "Semantic static security analysis",
    executable: "codeql",
    licenseNote:
      "Automated CI/CD use is subject to GitHub CodeQL licensing/plan terms; enable only when permitted.",
    buildArgs: (root, outputFile) => [
      "database",
      "analyze",
      "--format=sarif-latest",
      "--output=" + outputFile,
      root,
    ],
  },
  {
    id: "semgrep",
    tier: "A",
    version: "1.179.0",
    outputFormat: "sarif-2.1.0",
    purpose: "Pattern-based security, correctness and maintainability analysis",
    executable: "semgrep",
    buildArgs: (root, outputFile) => [
      "scan",
      "--sarif",
      "--output",
      outputFile,
      "--config",
      "auto",
      root,
    ],
  },
  {
    id: "osv-scanner",
    tier: "A",
    version: "2.6.0",
    outputFormat: "sarif-2.1.0",
    purpose: "Dependency vulnerability evidence",
    executable: "osv-scanner",
    buildArgs: (root, outputFile) => [
      "scan",
      "--format",
      "sarif",
      "--output",
      outputFile,
      root,
    ],
  },
  {
    id: "trivy",
    tier: "A",
    version: "0.74.0",
    outputFormat: "sarif-2.1.0",
    purpose: "Vulnerability, misconfiguration, secret and supply-chain scanning",
    executable: "trivy",
    buildArgs: (root, outputFile) => [
      "fs",
      "--format",
      "sarif",
      "--output",
      outputFile,
      root,
    ],
  },
  {
    id: "actionlint",
    tier: "A",
    version: "1.7.12",
    outputFormat: "json",
    purpose: "GitHub Actions workflow validation",
    executable: "actionlint",
    buildArgs: (root) => ["-format", "{{json .}}", root],
  },
  {
    id: "dependency-cruiser",
    tier: "A",
    version: "18.1.0",
    outputFormat: "json",
    purpose: "Architecture dependency graph and rule violations",
    executable: "depcruise",
    buildArgs: (root, outputFile) => [
      root,
      "--output-type",
      "json",
      "--output-to",
      outputFile,
    ],
  },
  {
    id: "knip",
    tier: "A",
    version: "6.31.0",
    outputFormat: "json",
    purpose: "Dead code, unused exports and dependencies",
    executable: "knip",
    buildArgs: (_root, outputFile) => [
      "--reporter",
      "json",
      "--output",
      outputFile,
    ],
  },
  {
    id: "scorecard",
    tier: "B",
    version: "5.5.0",
    outputFormat: "json",
    purpose: "Repository and supply-chain security posture",
    executable: "scorecard",
    buildArgs: (_root, outputFile) => ["--format", "json", "--output", outputFile],
  },
  {
    id: "syft",
    tier: "B",
    version: "1.54.0",
    outputFormat: "spdx-2.3",
    purpose: "SBOM generation",
    executable: "syft",
    buildArgs: (root) => [root, "-o", "spdx-json"],
  },
  {
    id: "gitleaks",
    tier: "B",
    version: "PIN_AT_ADOPTION",
    outputFormat: "json",
    purpose: "Secret detection including history-aware scans",
    executable: "gitleaks",
    buildArgs: (root, outputFile) => [
      "detect",
      "--source",
      root,
      "--report-format",
      "json",
      "--report-path",
      outputFile,
      "--redact",
    ],
  },
] as const;

export function getToolDefinition(toolId: string): ToolDefinition {
  const definition = TDI_TOOLCHAIN.find((tool) => tool.id === toolId);
  if (!definition) throw new Error("TDI_TOOL_NOT_REGISTERED:" + toolId);
  return definition;
}
